lib/roadworker/dsl.rb

Features depend on filepath+lineno (such as `__FILE__`, `__dir__`) didn't work 
because they were not set when evaluating a file content.

Specify path, lineno on evaling first file

---

.travis.yml
bin/roadwork
lib/roadworker/client.rb
lib/roadworker/collection.rb
lib/roadworker/dsl.rb
lib/roadworker/route53-exporter.rb
lib/roadworker/route53-ext.rb
lib/roadworker/route53-health-check.rb
lib/roadworker/route53-wrapper.rb
roadworker.gemspec
spec/roadworker_create_private_spec.rb
spec/roadworker_create_spec.rb
spec/roadworker_delete_private_spec.rb
spec/roadworker_delete_spec.rb
spec/roadworker_geo_spec.rb
spec/roadworker_health_check_create_spec.rb
spec/roadworker_health_check_delete_spec.rb
spec/roadworker_health_check_update_spec.rb
spec/roadworker_mix_spec.rb
spec/roadworker_target_hz_spec.rb
spec/roadworker_update_private_spec.rb
spec/roadworker_update_spec.rb
spec/spec_helper.rb

I'm testing this branch with my personal account.
Maybe many tests fail...

Upgrade aws-sdk to v2

---

lib/roadworker/route53-ext.rb

I want to add alias record that pointed to ELB name owned by other AWS account.
AWS API require hosted_zone_id, so specify it in Routefile like following.
```
rrset "elb.example.com.", "A" do
dns_name "some-other-accounts-elb.ap-northeast-1.elb.amazonaws.com.", :hosted_zone_id => 'ABCDEFGHIJKLMN'
end
```

support cross account ELB Alias

---

bin/roadwork

Hi.
I found file name typo when exporting with `--split` option.
missing 'a'.
`*.privte.route`
`*.private.route`
roadworker is very useful tool and it has helped my work.
thank you.

fixed private domain route file name.

---

bin/roadwork

Hi, Sugawara san
I tried to export route53 record but got following error.
```sh
$ roadwork --version
roadwork 0.5.5
$ export AWS_ACCESS_KEY_ID='AKxxxxxxxxxxxxxxxxxxxxxx'
$ export AWS_SECRET_ACCESS_KEY='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
$ roadwork -e
[ERROR] Aws::Errors::MissingRegionError: missing region; use :region option or export region name to ENV['AWS_REGION']
```
I think that [it needs to specify region using AWS SDK v2](http://docs.aws.amazon.com/sdkforruby/api/Aws/Route53/Client.html). Therefore, I added to specify region.
Please confirm.
Thank you.

Add specify region

---

lib/roadworker/route53-ext.rb
spec/roadworker_create_spec.rb

```ruby
hosted_zone 'example.com.' do
rrset 'example.com.', 'A' do
ttl 300
resource_records(
'xxx.xxx.xxx.xxx'
)
end
rrset 'alias.example.com.', 'A' do
dns_name 'example.com.'
end
end
```

Enable to specify rrset which is alias of `@` in the same hz

---

bin/roadwork

Multiple private zones with the same zone name (i.e. for testing, staging,
production) are exported to the same file when using the `--split`
option.
By adding the `vpc_id` to the `route_file_basename`, multiple private
zones with the same zone name can be correctly exported to separate
files when using the `--split` option.

Support multiple private zones w/ same zone name

---

lib/roadworker/dsl-tester.rb

`("A".."z").to_a` contains "[", "\\", "]", "^", "_", "`". 
These characers are bad for net/dns.
I get an error such as the following
`asterisk-of-wildcard-clP^sa6].hoge.jp. A: Bad query string`
Thanks! nice work.

Remove bad character from wildcard's rand_str

---

README.md
lib/roadworker/client.rb
lib/roadworker/dsl.rb
spec/roadworker_create_spec.rb
spec/roadworker_delete_spec.rb
spec/roadworker_update_spec.rb

Adding new DSL methods for hosted zone: `ignore`, `ignore_under`.
Both allow excluding rrset matches against defined patterns from management of Roadworker. If An actual rrset's name matches against a defined pattern, Roadworker ignores them even if it's different from DSL.
This will be useful some rrsets are managed under other tools or scripts in a same hosted zone; because current Route 53 doesn't allow associating nested private hosted zone in a same VPC.
``` ruby
hosted_zone "winebarrel.jp." do
ignore "ignore.winebarrel.jp"
ignore /^regexp-ignore/
ignore_under "ignore2.winebarrel.jp"
end
```

Support ignoring rrsets

---

lib/roadworker/dsl-converter.rb

Hi Sugawara-san !
Thank you for awesome tools.
I found that `GeoLocation` export does not work like this.
```ruby
rrset "hoge.example.com.", "A" do
set_identifier "1234"
ttl 300
geo_location #<struct Aws::Route53::Types::GeoLocation continent_code="AF", country_code=nil, subdivision_code=nil>
resource_records(
"127.0.0.1"
)
end
```
I think that this is `output_rrset` problem.
`value` is `Aws::Route53::Types::GeoLocation` object not `Hash` in `output_rrset`.
```ruby
rrset "hoge.example.com.", "A" do
set_identifier "1234"
ttl 300
geo_location :continent_code=>"AF"
resource_records(
"127.0.0.1"
)
end
```
- https://github.com/winebarrel/roadworker/pull/15
This is my just idea, so "close PR" is OK.
Please review if PR has side-effect.
Thanks 🙇

Fixed export with GeoLocation

---

lib/roadworker/route53-ext.rb

Route 53 alias is also available for Elastic Beanstalk. I wanted to EB support, made a PR.
https://aws.amazon.com/jp/about-aws/whats-new/2016/01/aws-elastic-beanstalk-adds-support-for-amazon-route-53-aliasing/
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customdomains.html

Support Alias for Elastic Beanstalk

---

lib/roadworker/client.rb

WHEN two private zones with the same name (say `example.local`) exist
AND these zones are assocaited to the different VPCs (`[vpc1]`, `[vpc2]`)
`[normalize_name(i.name), i.vpcs.empty?]` is the same value `["example.local", true]` and hashes `expected` and `actual` has only one key for `example.local` zone.
This patch changes the latter in the array, and the hash key will be `["example.local", ["vpc1]]` and `["example.local", ["vpc2"]]`, in order to deal with these zones as different ones.
It should be unique, since a private zone can be associated to only one VPC with the same name.
`export` can handle multiple private zones in #33 but `apply` looks not then.

Deal with zones with the same name associated to different VPCs correctly

---

lib/roadworker/client.rb
lib/roadworker/dsl-converter.rb
lib/roadworker/dsl.rb
lib/roadworker/route53-exporter.rb

When we give the following change
```patch
hosted_zone "example.com." do
vpc "us-east-1", "vpc-xxxxxxxx"
+  vpc "us-east-1", "vpc-yyyyyyyy"
end
```
roadworker tries to recreate the hosted zone.
```
$ roadwork --apply --dry-run --force
Apply `Routefile` to Route53 (dry-run)
Create Hostedzone #<struct Aws::Route53::Types::VPC vpc_region="us-east-1", vpc_id="vpc-xxxxxxxx">: example.com (dry-run)
Associate #<struct Aws::Route53::Types::VPC vpc_region="us-east-1", vpc_id="vpc-yyyyyyyy">: example.com (dry-run)
Delete Hostedzone: example.com. (dry-run)
No change
```
This destructive behavior seems to have been introduced by https://github.com/codenize-tools/roadworker/pull/54 for dealing with the case where we have multiple private hosted zones with the same name.
By applying this patch, it …

Optionally accept hosted zone ID in DSL

---

lib/roadworker/route53-ext.rb
roadworker.gemspec

AWS recommends library maintainers use service specific gems.
cf. https://aws.amazon.com/blogs/developer/upgrading-from-version-2-to-version-3-of-the-aws-sdk-for-ruby-2/
roadworker can't coexists with gems which depend on aws-sdk V3, so I think roadworker should use aws-sdk V3.

Use aws-sdk V3

---

lib/roadworker/dsl-tester.rb
roadworker.gemspec

Hi!
As reported in #61, the `--test` option of roadworker against ruby2.4 shows the following warnings.
```
$ bundle exec ./bin/roadwork -t
/Users/hoshino/src/github.com/codenize-tools/roadworker/vendor/bundle/ruby/2.4.0/gems/net-dns2-0.8.7/lib/net/dns/rr/types.rb:127: warning: constant ::Fixnum is deprecated
/Users/hoshino/src/github.com/codenize-tools/roadworker/vendor/bundle/ruby/2.4.0/gems/net-dns2-0.8.7/lib/net/dns/rr/classes.rb:35: warning: constant ::Fixnum is deprecated
```
But net-dns gem, which is the cause of the warning, seems to be no longer maintained.
So, this PR replaces the net-dns gem with [dnsruby](https://github.com/alexdalitz/dnsruby).
I confirmed that the all specs passed at my environment.
This PR may also fix #55.

Replace net-dns with dnsruby

---

lib/roadworker/dsl-tester.rb

Thanks to the non-standard Alias record type that has been introduced by
AWS Route 53 one could get fake diffs while running `--test`.
This had no effect on the actual `--apply` command since nothing would
change but could mislead the user that the record is going to be updated.
The root cause is the lack of the actual TTL field on the Alias records so
when the `dsl-tester` tried to check if the actual and expected values
match it showed that they are different.
Since the A (ipv4) record (returned by the query) has TTL and the Alias has not.
Solution:
I've introduced a `check_ttl` variable that sets if the TTL values
should be checked or not. The code simply disables ttl check if it's an
Alias record.
Signed-off-by: Gergő Nagy <contact@gergonagy.com>

dsl-tester: A(Alias) fake diff fixed

---

lib/roadworker/route53-ext.rb

I got the following error when I added records for API Gateway with a Custome Domain. 
```
roadwork -a --target '^xxxxxxx.com$'
Apply `Routefile` to Route53
`dualstack` prefix is used in the actual DNS name: *.xxxxxx.com. A
Create ResourceRecordSet: yyyyyyyyyyyyyy.xxxxxx.com A
[ERROR] ArgumentError: missing required parameter params[:change_batch][:changes][0][:resource_record_set][:alias_target][:hosted_zone_id]
```
To resolve the above errors, I'd like to fix the argument used in `apigw_dns_name_to_alias_target` method.

Fix argument for apigw_dns_name_to_alias_target

---

lib/roadworker/route53-ext.rb

I got the following error when I added records for API Gateway with a Custome Domain. 
```
roadwork -a --target '^xxxxxxx.com$'
Apply `Routefile` to Route53
`dualstack` prefix is used in the actual DNS name: *.xxxxxx.com. A
Create ResourceRecordSet: yyyyyyyyyyyyyy.xxxxxx.com A
[ERROR] ArgumentError: missing required parameter params[:change_batch][:changes][0][:resource_record_set][:alias_target][:hosted_zone_id]
```
In https://github.com/codenize-tools/roadworker/pull/70, I fixed argument for  `apigw_dns_name_to_alias_target` method but I didn't add region variable for the method. Let me fix the part in this PR.

Add missing region variable

---

.travis.yml

See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

CI: Removes an old setting from Travis

---

lib/roadworker.rb
lib/roadworker/batch.rb
lib/roadworker/client.rb
lib/roadworker/dsl.rb
lib/roadworker/log.rb
lib/roadworker/route53-ext.rb
lib/roadworker/route53-wrapper.rb
lib/roadworker/utils.rb

Current roadworker issues 1 ChangeResourceRecordSets API (change batch) per 1 ResourceRecordSet. This doesn't allow:
- Rollback of entire change when there's an error
- This is the nature and benefit of the API!  https://docs.aws.amazon.com/en_pv/Route53/latest/APIReference/API_ChangeResourceRecordSets.html
- Atomic transision between CNAME and other RR types, or setting/removing set_identifier 
- CNAME doesn't allow any RR of other types exist on the same name. To allow transision of some DNS name between CNAME and other RR type atomically, we have to issue DELETE/UPDATE changes in a single change batch.  Previously it wasn't implemented correctly because every changes were submitted in an individual batch.
By making changes in a single change batch, these will be resolved. Also, this …

Submit single change batch per hosted zone on apply

---

lib/roadworker/route53-wrapper.rb

When I tried to delete hosted zone, I got the following error.
```
$ roadwork -a --dry-run --target '^foo.bar$' --force
Apply `Routefile` to Route53 (dry-run)
Delete Hostedzone: foo.bar. (dry-run)
[ERROR] NoMethodError: undefined method `delete' for #<Aws::Route53::Types::ResourceRecordSet:0x00007ff81a9a3278>
```
ResourceRecordSetWrapper#delete was removed in https://github.com/codenize-tools/roadworker/commit/a3876f69ef79ec13c7d999351eaf33b8af2d6b43#diff-f8d164d49d5178a7c052045f1e269148.
So I changed to submit a batch request to delete records associated with
the target hosted zone as well.
@sorah Could you review?

Delete hosted zone and its records correctly

---

lib/roadworker/batch.rb
spec/roadworker_batch_spec.rb
spec/spec_helper.rb

Suppose you have an ALIAS record.
```ruby
hosted_zone 'winebarrel.jp.' do
rrset 'test.winebarrel.jp.', 'A' do
dns_name 'roadworker.cloudfront.net.'
end
end
```
When you'd like to change the ALIAS record to CNAME record, ALIAS deletion must be prioritized over CNAME creation.
```ruby
hosted_zone 'winebarrel.jp.' do
rrset 'test.winebarrel.jp.', 'CNAME' do
ttl 300
resource_records('example.com.')
end
end
```
```
% roadwork --apply
Apply `Routefile` to Route53
=== Change batch: winebarrel.jp. | /hostedzone/ZXXXXXXXXXXXXX
Create ResourceRecordSet: test.winebarrel.jp. CNAME
Delete ResourceRecordSet: test.winebarrel.jp. A
[ERROR] Aws::Route53::Errors::InvalidChangeBatch: [RRSet of type CNAME with DNS name test.winebarrel.jp. is not permitted as it conflicts with other records with the same DNS …
```

Fix priority between CNAME change and ALIAS change 

---

lib/roadworker/route53-ext.rb

Added definition of hosted_zone_id for us-east-2, 
because ALIAS configuration for us-east-2 ALB failed on 0.5.13

feat: support us-east-2 hosted zone name id

---

bin/roadwork

When an error is thrown without the `--debug` option, the current `roadwork` command only prints the error message without its backtrace, making it hard to debug. This patch removes the `rescue`s and allows errors to be raised as they are.

Show backtraces when an error is raised

---

roadworker.gemspec

it'll be removed from stdlib soon

add ostruct as a explicit dependency

---

lib/roadworker.rb
lib/roadworker/route53-wrapper.rb
roadworker.gemspec

Route 53 appears to retain the initial string representation even if client upserts with a different string representation when both represents the same address (e.g. 2001:0db8::a => 2001:db8::a, but route53 still returns 0db8 in further read API calls). Parse string representation and compare the actual addresses for difference check.

check AAAA record identicalness using IPAddr
